### PR TITLE
Lift 3.1 update

### PR DESCRIPTION
**Pull request by davenatx**
When I attempted to use 0.9.3 with Lift 3.1.0 I received the following exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: net.liftweb.common.Box.openOrThrowException(Ljava/lang/String;)Ljava/lang/Object;
  at net.liftmodules.ng.AngularJsRest$.init(AngularJsRest.scala:13)
```

After compiling my own version and publishing it locally for Lift 3.1.0 it worked as expected.

This pull request updates the project to also build with Lift 3.1.0.  I did attempt to add support for Scala 2.12 but realized ScalaTest only has version 3.x available for Scala 2.12, 2.11 and 2.10. It seems the should matchers were deprecated between versions 2.x and 3.x.  Unfortunately, since 3.x does not support Scala < 2.10 I am not sure how to proceed.  Maybe we should follow the Lift project's lead and start only supporting Scala 2.11 and 2.12 with future releases?

### CODE REVIEW

**Comment by joescii** [comment]
Hey David! So simply recompiling it fixes the issue? This happens occasionally when building for the milestone releases since we allow breaking changes.

**Comment by davenatx** [comment]
Hey Joe!  Yes, it appears recompiling for 3.1 fixes the issue.  For what it is worth, I was successfully using 0.9.3 with Lift 3.0.1.  So, whatever caused the issue must have been introduced in 3.1.

**Comment by joescii** [comment]
Dave! Sorry for the super slow response. I have been absolutely swamped, and I knew that it would take me extra time to work on this since I am using a new development environment.

Once I revisited this yesterday, it occurred to me that we shouldn't be surprised by this issue. We never guarantee binary compatibility across Lift versions, so something compiled for 3.0 might not work with 3.1.

The real solution is to cross compile this for 3.1. I have done so in [branch lift31](https://github.com/joescii/lift-ng/tree/lift31). I cut support for Scala 2.9.x. I ran into issues compiling the compiler (lol) on JVM 8, and I'm like you in that I think it's time to pull the plug.

Publish that branch locally (can use `publish.sh` to cross compile and publish all the supported combinations). Set your project to use version `0.9.3-SNAPSHOT` but make sure you update the artifact name to have `3.1` rather than `3.0`.

I'm going to open an issue for 2.12 support. The scalaz dependency isn't released at the version we are using. I only used it for one little thing which frankly could be implemented using a plain ol' mutable hash map. I was getting carried away playing with things, but this project would be better if it didn't introduce scalaz into the class path.

**Comment by davenatx** [comment]
Hey Joe, no worries and thanks for the update!  I know you are busy and believe you are no longer using this project for your own stuff so if there is anything I can do to help/contribute, please let me know.

**Comment by joescii** [comment]
If you could, try publishing locally and all to see it works for your project as I outlined in the previous comment just as a double check.

**Comment by davenatx** [comment]
Hey Joe, I checked out the lift31 branch, bumped the liftVersion in build.sbt to 3.1.0-M1 and did a publishLocal.  Then I updated my project to use lift-ng 0.9.3-SNAPSHOT and everything worked as expected.

**Comment by joescii** [comment]
Lift 3.1.0-M2 should be released very soon. I'm going to wait for that and do a release.

**Comment by joescii** [comment]
Just released 0.9.3 cross compiled against Lift 3.1.0-M2. Note that it's possible this conflicts with your M1 build of Lift.
